import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, DataSource, Like } from 'typeorm';
import { Compra } from './entities/compra.entity';
import { CompraDetalle } from './entities/compra-detalle.entity';
import { Parte } from '../parte/entities/parte.entity';
import { Proveedor } from '../proveedor/entities/proveedor.entity';
import { CreateCompraDto } from './dto/create-compra.dto';
import { NotificacionService } from '../notificacion/notificacion.service';
import { Notificacion } from '../notificacion/entities/notificacion.entity';

@Injectable()
export class CompraService {
  constructor(
    @InjectRepository(Compra)
    private readonly compraRepository: Repository<Compra>,
    @InjectRepository(Proveedor)
    private readonly proveedorRepository: Repository<Proveedor>,
    private readonly dataSource: DataSource,
    private readonly notificacionService: NotificacionService,
  ) {}

  async create(createCompraDto: CreateCompraDto, usuarioId: number): Promise<Compra> {
    const { proveedorId, numeroFactura, fecha, ivaPorcentaje, comentario, detalles } = createCompraDto;

    // 1. Verify supplier
    const proveedor = await this.proveedorRepository.findOneBy({ id: proveedorId });
    if (!proveedor) {
      throw new NotFoundException(`Proveedor con ID ${proveedorId} no existe.`);
    }
    if (!proveedor.estado) {
      throw new BadRequestException(`El proveedor "${proveedor.nombre}" está inactivo.`);
    }

    if (!detalles || detalles.length === 0) {
      throw new BadRequestException('La compra debe contener al menos un detalle / producto.');
    }

    // 2. Perform Transaction to ensure consistency
    const savedCompra = await this.dataSource.transaction(async (manager) => {
      let calculatedSubtotal = 0;

      // Temporary collections to process
      const itemsToProcess = [];
      const updatedPartes: Parte[] = [];

      for (const item of detalles) {
        // Fetch product within transaction
        const parte = await manager.findOneBy(Parte, { id: item.parteId });
        if (!parte) {
          throw new NotFoundException(`El repuesto con ID ${item.parteId} no existe.`);
        }
        if (parte.unidadMedida === 'Servicio') {
          throw new BadRequestException(`El item "${parte.nombre}" es un servicio y no puede comprarse en almacén.`);
        }

        const lineQty = Number(item.cantidad);
        const linePrice = Number(item.precioUnitario);
        
        if (lineQty <= 0) {
          throw new BadRequestException(`La cantidad para "${parte.nombre}" debe ser mayor a 0.`);
        }
        if (linePrice < 0) {
          throw new BadRequestException(`El precio para "${parte.nombre}" no puede ser negativo.`);
        }

        const lineSubtotal = lineQty * linePrice;
        calculatedSubtotal += lineSubtotal;

        // Dynamic stock addition
        parte.stock = Number(parte.stock || 0) + lineQty;

        // Dynamic cost update based on user decision
        if (item.actualizarCosto) {
          parte.costo = linePrice;
        }

        // Add to update queues
        updatedPartes.push(parte);
        itemsToProcess.push({
          parte,
          cantidad: lineQty,
          precioUnitario: linePrice,
          subtotal: lineSubtotal,
          actualizarCosto: !!item.actualizarCosto,
        });
      }

      // Save all updated parts
      for (const updatedParte of updatedPartes) {
        await manager.save(Parte, updatedParte);
      }

      // Calculate taxes and grand total
      const rate = Number(ivaPorcentaje) / 100;
      const calculatedIvaMonto = calculatedSubtotal * rate;
      const calculatedTotal = calculatedSubtotal + calculatedIvaMonto;

      // 1. Save the Compra header first to get its autogenerated ID
      const compraRecord = manager.create(Compra, {
        numeroFactura,
        fecha: new Date(fecha),
        subtotal: calculatedSubtotal,
        ivaPorcentaje: Number(ivaPorcentaje),
        ivaMonto: calculatedIvaMonto,
        total: calculatedTotal,
        comentario,
        estado: 'Completado',
        proveedorId,
        usuarioId,
      });
      const compraGuardada = await manager.save(Compra, compraRecord);

      // 2. Loop and save each CompraDetalle referencing the header ID
      const detallesGuardados: CompraDetalle[] = [];
      for (const item of itemsToProcess) {
        const detalleRecord = manager.create(CompraDetalle, {
          compraId: compraGuardada.id,
          parteId: item.parte.id,
          cantidad: item.cantidad,
          precioUnitario: item.precioUnitario,
          subtotal: item.subtotal,
          actualizarCosto: item.actualizarCosto,
        });
        const detalleGuardado = await manager.save(CompraDetalle, detalleRecord);
        detallesGuardados.push(detalleGuardado);
      }

      // Link details back to the header object for return response
      compraGuardada.detalles = detallesGuardados;
      return compraGuardada;
    });

    // 3. Post-Transaction: Async Alerte Cleanups
    // Since stock increased, resolve active low-stock notifications for these products if they are now above the minimum.
    this.resolveLowStockAlerts(savedCompra.id).catch((err) => {
      console.error('Error post-compra resolviendo alertas de stock:', err);
    });

    return savedCompra;
  }

  private async resolveLowStockAlerts(compraId: number): Promise<void> {
    try {
      const compra = await this.compraRepository.findOne({
        where: { id: compraId },
        relations: ['detalles', 'detalles.parte'],
      });
      if (!compra) return;

      const notiRepo = this.compraRepository.manager.getRepository(Notificacion);

      for (const d of compra.detalles) {
        const parte = d.parte;
        const currentStock = Number(parte.stock);
        const stockMin = Number(parte.stockMinimo);

        if (currentStock > stockMin) {
          // Find unread notification that contains this part's name
          const notifications = await notiRepo.find({
            where: {
              leido: false,
              isDeleted: false,
            },
          });

          for (const noti of notifications) {
            if (noti.mensaje && noti.mensaje.includes(parte.nombre)) {
              noti.leido = true;
              await notiRepo.save(noti);
            }
          }
        }
      }
    } catch (error) {
      console.error('Failed to resolve low stock alerts for purchase:', error);
    }
  }

  async findAll(query: { limit?: number; page?: number; search?: string }): Promise<{ items: Compra[]; total: number }> {
    const limit = query.limit || 10;
    const page = query.page || 1;
    const skip = (page - 1) * limit;

    const where: any = {};
    if (query.search) {
      where.numeroFactura = Like(`%${query.search}%`);
    }

    const [items, total] = await this.compraRepository.findAndCount({
      where,
      relations: ['proveedor', 'usuario'],
      order: { fecha: 'DESC' },
      take: limit,
      skip,
    });

    return { items, total };
  }

  async findOne(id: number): Promise<Compra> {
    const compra = await this.compraRepository.findOne({
      where: { id },
      relations: ['proveedor', 'usuario', 'detalles', 'detalles.parte'],
    });

    if (!compra) {
      throw new NotFoundException(`Compra con ID ${id} no encontrada.`);
    }

    return compra;
  }

  async anulacion(id: number): Promise<Compra> {
    const compra = await this.findOne(id);
    if (compra.estado === 'Anulado') {
      throw new BadRequestException('Esta compra ya se encuentra anulada.');
    }

    // Rollback stock when purchase is cancelled
    return await this.dataSource.transaction(async (manager) => {
      for (const d of compra.detalles) {
        const parte = await manager.findOneBy(Parte, { id: d.parteId });
        if (parte) {
          parte.stock = Math.max(0, Number(parte.stock || 0) - Number(d.cantidad));
          await manager.save(Parte, parte);
        }
      }

      compra.estado = 'Anulado';
      const updated = await manager.save(Compra, compra);

      // Re-trigger low stock checks after rollback
      for (const d of compra.detalles) {
        this.notificacionService.checkAndNotificarStockBajo(d.parteId).catch((err) => {
          console.error(`Error re-evaluando stock post-anulación del repuesto ${d.parteId}:`, err);
        });
      }

      return updated;
    });
  }
}
